# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro_isbn', models.CharField(max_length=13)),
                ('slug', models.SlugField(blank=True, max_length=13, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=True)),
            ],
        ),
    ]
